### PR TITLE
70 move `ccissdev` to its own repo and rename to `ccissr`

### PR DESCRIPTION
**Pull request by CeresBarros**
https://github.com/bcgov/CCISS_ShinyApp/issues/70

### CODE REVIEW

**Comment by CeresBarros** [comment]
@cmahony this is now ready to merge -- local tests seem to be okay, but perhaps you could pull `70-move-ccissdev-to-its-own-repo-and-ren` and test on your side?

**Comment by cmahony** [comment]
@CeresBarros your refactor of the package dependencies seems less robust. i've had to delete some lock files and still getting 
```
> shiny::runApp('spatial_app')
Error: package ‘htmltools’ does not have a namespace
```

**Comment by CeresBarros** [comment]
yes, that happens because `Require` will try to install/update packages -- it's less robust if you have them installed already, but less hands-on if you don't have the packages (which was my case). Also, if we use GHA to test the apps, Require will make our lives easier to set up the system.
Those LOCK problems are due to having multiple R sessions open., and are a Windows problem unrelated to `Require` -- they don't seem to happen on Unix systems. 
To fix `Error: package ‘htmltools’ does not have a namespace` go to the library folder and delete the `htmltools` folder.

**Comment by cmahony** [comment]
@CeresBarros i've tested and it works on my end.

**Pull request merged**
